### ISSUE TITLE
When scrolling up and down, sometimes, the reused collection views are not refreshed and show incorrect colour patterns from other row

### ISSUE THREAD

**Issue by ernestng** [ashfurrow/Collection-View-in-a-Table-View-Cell#1]
Just watch the first row. After scrolling up & down, it changes randomly. After some debugging, I found out that the data source of the collection views are not called all the times for reused collection views.

I can fix the problem by adding this line  
cell.collectionView.reloadData()
at tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) delegate. 

I hope there is a better way or a good explanation of the current behaviour. 

BTW. Thank you for the blog. I am learning a lot.

**Comment by ashfurrow** [comment]
Ah, interesting. Thanks for reporting! I'll take a look.

**Comment by ashfurrow** [comment]
Cool, so I put `reloadData()` in the `setCollectionViewDataSourceDelegate` function. I had assumed that setting the datasource would call `reloadData`, but I suspect that UIKit notices I'm setting the datasource to be the same object as it was before, and isn't reloading the data. Thanks again for pointing this out!

**Comment by ashfurrow** [comment]
OK, I've updated the blog post as well: https://github.com/ashfurrow/blog/commit/1782a4d5c63adb7f687ec0a936d4ef0759e07495

**Comment by PPacie** [comment]
Guys, this approach works but has a performance side effect. I am using it in the following app: https://itunes.apple.com/us/app/surf-movies/id1075162731?mt=8 

When you scroll vertically in the Home screen you will notice the lags due to the `reloadData()` in the `setCollectionViewDataSourceDelegate`. I have tested commenting that line out and the vertical scroll becomes smooth.

I have an iPhone 5S, perhaps you don't notice it in most recent devices. But still that reloadData() is super expensive there.

PS: I just noticed it, in case I come up with a solution will let you know.

**Comment by pupoo** [comment]
So i know this is beyond late, but this isnt loading the cells that are initially visible on screen.  if you scroll off and then back they display fine. 

The reloadData() isnt working and cant really access the setCollectionViewDataSourceDelegate function outside of willDisplay
