### ISSUE TITLE
setCollectionViewDataSourceDelegate in willDisplayCell

### ISSUE THREAD

**Issue by hipwelljo** [ashfurrow/Collection-View-in-a-Table-View-Cell#13]
Thanks for the excellent tutorial! It works very well. I am just curious why the call to setCollectionViewDataSourceDelegate is made in willDisplayCell as opposed to cellForRowAtIndexPath? I've put it in the latter and it seems to behave just fine. It seems it would be more appropriate in cellForRowAtIndexPath so that it is ready before the user scrolls to see it. It doesn't seem to be great to reload the collection view just right before it's going to be displayed. Just curious if there is a reason I'm not seeing. Thanks!

**Comment by ashfurrow** [comment]
Hey there! Certain layout calls need to be made in willDisplyCell because it isn't until then that the cell has a valid frame, supervise, etc. At one point in time, calling reloadData on the collection view here was necessary; it's possible newer versions of iOS remove this requirement.  

I still like it though. cellForRowAtIndexPath is really for configuring the cell so that it can later be displayed, and willDisplayCell is for configuring the cell _to_ be displayed, if that makes sense. I like the distinction, but it's a personal preference. I've been burned by cellForRow too many times to trust it 😉
--  
Ash Furrow
https://ashfurrow.com/

**Comment by jordanhbuiltbyhq** [comment]
Okay, thanks for explaining that. That makes sense. :)

**Comment by hipwelljo** [comment]
Okay, thanks for explaining that. That makes sense. :)

**Comment by ashfurrow** [comment]
No problem! Re-open, or open a new issue, if I can be of further help. Cheers!
