### ISSUE TITLE
Swift 3 migration

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/Collection-View-in-a-Table-View-Cell#28]
Hopefully not too difficult, haven't looked into it yet.

**Comment by kurdyukovp** [comment]
Hello Ash, do you have any news?

**Comment by ashfurrow** [comment]
I have not, I'll try to get to it this week.

**Comment by BabyAzerty** [comment]
For those having a problem converting functions with protocol conformance, here is an example for the `TableViewCell.swift`:

    func prepareCollectionView(_ delegate: UICollectionViewDelegate, _ dataSource: UICollectionViewDataSource, forRow row: Int) {
    //Or func prepareCollectionView(_ delegateAndDataSource: UICollectionViewDelegate & UICollectionViewDataSource, forRow row: Int) {
        collectionView.delegate = delegate
        collectionView.dataSource = dataSource
        collectionView.tag = row
        collectionView.setContentOffset(collectionView.contentOffset, animated:false) // Stops collection view if it was scrolling.
        collectionView.reloadData()
    }

**Comment by xuyang1993** [comment]
Hi, i have an question: if the collection view cell numberOfItemsInSection are different, and when i scroll collection view  will crash due to Index out of range.
I found the problem that when i scroll the tableview the collection view cell index path updated to the bottom one, but the collection view i scrolled is top one and it does't remember the numberOfItemsInSection, so it will crash due to Index out of range .

Do you have any idea how to solve this problem?
Thanks
