### ISSUE TITLE
setCollectionViewDataSourceDelegate in cellForRowAt instead of willDisplay?

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [ashfurrow/Collection-View-in-a-Table-View-Cell#47]
I'm curious if there's a reason you're calling `setCollectionViewDataSourceDelegate()` from within `tableView(_:willDisplay:forRowAt:)` as opposed to `tableView(_:cellForRowAt:)`? Thanks! This is an excellent resource.

**Comment by ashfurrow** [comment]
Great question – it's because it felt like a more appropriate callback spot. `tableView(_:cellForRowAt:)` is supposed to return a configured cell, but that doesn't mean that the cell will be visible. `tableView(_:willDisplay:forRowAt:)` is for when the cell is about to be rendered. Either should work though 👍
